## 数据库连接
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/com.clipper.market?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: ok

## 图片真实存储路径
#sys.fileRealPath=D\:/file/
## 图片相对访问路径前缀
#sys.fileAccessPath=/file/


## 支付宝参数
#ali.app_id=2016091400511118
#ali.merchant_private_key=MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCBM3onbQkGZgRVJvNDHRGKTQeCkosrrglu+XcPUelhIq0LfDDVof16EyX5a6gk4oIqQv4KcoP/FSq6rO+IkTJtrsDnCNwvNBXHJHGKmF8WZAedV2kfPoOF47X1xnDTg2ZIrPyOKiJ2FrotBg+qYzIOb2eUHoCXQ9L8kjdg6y7BUgJ+XsomAHkzk4vDaUpFf1n6uE4Arv6Y28EaHwMRqpFLK24jZkPLs/0jwSWBGHPuyqgkHSxsFrwucgZykGBwlEmbsL1zV9WMt94OR6dY3ZpVvCcL2NRPqeAixPBIljW6XUJQy4Q61K3b7SDzByM8KAv/zUYCK1kQAZdR8j2xfesVAgMBAAECggEAftZca2wdWgy44CeW1SIqYA1y+/qFaeI3HJ0HByEw7c0u+IF5J6EZyMgXlZ7cuSktA/Q0lWkKsFbFVfIETZvNV+QhOC54ilalspTSam9fmgmleA+iAaxLThvYPGoNxXfP6DT6004F+swhBaZXprwvHgC8PKsdLmLFNHMOrrTzd5BqPWzwMyeNM3I/Hpd4cwZjuS/faWGkM+1wxC4ydn9nKSTGe4U6vJa7aw1c2ocbtumTh4NvJgnvRAj6mxYJEHgMMOE4PSPJLhykAmdkl8MxSPlv7uYzhMFZSHfeRUktcM+wa6NqJD/MOVzE2ch6apO3GoRtv9BYYMTFM+Qefhjz2QKBgQDwAPgUkoPsoMlZYHFCEaBYj1e0DB5ePpWrKpIvwfE9iyNt26RDImmKTn1mCO4SsnkNL6RwTJK+Ahi3jUSHDKyQQ4VUckF6CN4rHmZthDeNSkO1LAljkQSv9zA8ecqItpIzh4GmX2+q8s+cJT7vLMui1pxBtwEcKwYICrB3Q6QeBwKBgQCJz/PYbHg16kISzlfr5OacQmdChB9gzU7D29WZOTII94W/GnRItJ37vizquK5UepnGPfOimJV4qZcnrbURopwMjJ1tc4nuCaHv3fgBb5VPqQsdVdu72y/jM5L05j/8lizzqw6Ohnu2rTQoiXMZmn9lMmieOURjEoeOcrXNAm2nAwKBgDPGYb4+ZUtU3Fr1nTk9iDPSqH7k5mA6bBtC0cqPsjUuoPQAIA2DjPUTPaYXYxSRf9/CWV0Ih9eJqD9gsFnZ+BgfGNJA27Mx2ou+wSX7EejfDoA1AcmC7Vnwn21McM7RY/TN1MBJclOUkgkDV/JM3ZlBZvAeRJUJCwINHEh+RRddAoGAGCAojx3GGaIt+P7Yk3paCMbzLsjUeWzXuh/1D8LciIdUibUG4GeGNLkBQgIcurtPyk20JiXSHPKLfK3DQhgWe3fuY2fToLFdARH5xb6UBAMS6ArM0eE4S+0OcAMS9pQPwISUoszWQY+mzuXpGXVbkgq2F+TsnO90fbKFMyOWsKMCgYApfDlWcKcVOctKEcYozQ/xbjSNDQmfIMf8FGjM58um/Hy1pWGTWcnlMHzvMXG+h6g3zE4zvW6TvyMtZN5GyYbB9BJ1XaPCQsi+tS93EnZTnMclBIg5t73tjyQkviFgOEX+HjU/JaPDBR9uCMT8zzKNxo0sXTjfKfmRbSBLqJ0luw==
#ali.alipay_public_key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1ibuO+rdnpgExCn09I3hmcwJKn7cdbqPTsPjnixcQSUf2KFhQ0DhIL+VeKj13AiAZSfgGvJTcsZ4HbfedRACofB0EFKSPcgBr4Pi3RX6fwpAyRqztelf0jl/HMqn0bkQTK3YDJMhJ+/jC2CVlm5qIZPqgRPZda23tw9aVsNy39HYc2gsTEFqEp6ayDXrak7pw7szf3JI3rAFgVDT4up/euEWcGKrzfHSJY6Hic58AIGJ8rSgribnNi6ZOfdcjMwnXaMhBigaJY+7oSroufJm++sE6Qfi0Yepp9dyWFrOv13c0VtV9xiMVjIgkEaMZUpZLjbkTFhx2IsI9p5TsXwwGwIDAQAB
#ali.return_url=http://xuhpay.free.idcfengye.com/alipay/return_url
#ali.notify_url=http://xuhpay.free.idcfengye.com/alipay/notify_url
#ali.sign_type=RSA2
#ali.charset=utf-8
#ali.gatewayUrl=https://openapi.alipaydev.com/gateway.do

#  微信支付参数信息
#wxpay.appID=wx123456789
#wxpay.mchID=wx123456789
#wxpay.key=wx123456789
