server:
  port: 7060

spring:
  redis:
    host: 127.0.0.1
    database: 6

  # datasoure MySQL JDBC
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: xuh
    password: root
    url: jdbc:mysql://xuh.com:3306/sso-auth?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false

# 注册到注册中心
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

#   actuator
management:
  #  endpoints:
  #    web:
  #      exposure:
  #        include: *
  endpoint:
    health:
      show-details: always


#ignore:
#  urls:
#    - /authentication/**
#    - /**/*.css
#    - /social
#    - /signin
#    - /signup
#    - /info
#    - /health
#    - /metrics/**
#    - /loggers/**
#    - /mobile/token