server:
  port: 7060

spring:
#  application Name
#  application:
#    name: auth-service
##    dev active
#  profiles:
#    active: dev

  # datasoure MySQL JDBC
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/xuhweb.auth-service?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/templates/

# 注册到注册中心
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

#ignore:
#  urls:
#    - /authentication/**
#    - /**/*.css
#    - /social
#    - /signin
#    - /signup
#    - /info
#    - /health
#    - /metrics/**
#    - /loggers/**
#    - /mobile/token